"""removed active column

Revision ID: 159e3daa0536
Revises: 44379fd7854a
Create Date: 2023-01-14 14:38:25.917583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159e3daa0536'
down_revision = '44379fd7854a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
