"""add order to show and if should be visible

Revision ID: 43dee70cb533
Revises: cded430a61b3
Create Date: 2023-06-22 12:21:34.473075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43dee70cb533'
down_revision = 'cded430a61b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('visible', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('section', sa.Column('order_to_show', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('subsection', sa.Column('sub_order_to_show', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('subsection', sa.Column('sub_visible', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subsection', 'sub_visible')
    op.drop_column('subsection', 'sub_order_to_show')
    op.drop_column('section', 'order_to_show')
    op.drop_column('section', 'visible')
    # ### end Alembic commands ###
