"""added cascade in constrant

Revision ID: 5d7e77543d08
Revises: 43dee70cb533
Create Date: 2023-06-24 16:02:50.975117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7e77543d08'
down_revision = '43dee70cb533'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subsection_section_id_fkey', 'subsection', type_='foreignkey')
    op.create_foreign_key(None, 'subsection', 'section', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subsection', type_='foreignkey')
    op.create_foreign_key('subsection_section_id_fkey', 'subsection', 'section', ['section_id'], ['id'])
    # ### end Alembic commands ###
