"""section title not unique

Revision ID: 71cb8fe5ef2d
Revises: c084726bc1ad
Create Date: 2023-02-27 20:07:19.317723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cb8fe5ef2d'
down_revision = 'c084726bc1ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('section_title_key', 'section', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('section_title_key', 'section', ['title'])
    # ### end Alembic commands ###
