"""updated datetime columns

Revision ID: cded430a61b3
Revises: eb28a3c855ca
Create Date: 2023-03-04 13:43:07.563205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cded430a61b3'
down_revision = 'eb28a3c855ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('section', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('subsection', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('subsection', 'sub_last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('subsection', 'sub_last_updated',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('subsection', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('section', 'last_updated',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('section', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
