"""id_title is unique

Revision ID: ef9c5268c706
Revises: ad9ada27d477
Create Date: 2023-02-25 16:41:22.994274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9c5268c706'
down_revision = 'ad9ada27d477'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'section', ['id_title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'section', type_='unique')
    # ### end Alembic commands ###
