"""id_title is not null

Revision ID: 707954e03604
Revises: ef9c5268c706
Create Date: 2023-02-25 16:46:44.362107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707954e03604'
down_revision = 'ef9c5268c706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section', 'id_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section', 'id_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
