"""added id_title

Revision ID: ad9ada27d477
Revises: af824ed60b30
Create Date: 2023-02-25 16:39:54.986691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9ada27d477'
down_revision = 'af824ed60b30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('id_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'id_title')
    # ### end Alembic commands ###
