"""title slug nullable false

Revision ID: c084726bc1ad
Revises: 359c7f22311c
Create Date: 2023-02-26 10:34:34.309645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c084726bc1ad'
down_revision = '359c7f22311c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section', 'title_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section', 'title_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
