"""added last_updated in section and subsection

Revision ID: eb28a3c855ca
Revises: 71cb8fe5ef2d
Create Date: 2023-03-01 19:28:17.757229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb28a3c855ca'
down_revision = '71cb8fe5ef2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('section', 'column1')
    op.add_column('subsection', sa.Column('sub_last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subsection', 'sub_last_updated')
    op.add_column('section', sa.Column('column1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('section', 'last_updated')
    # ### end Alembic commands ###
