FROM python:3.11.3-slim-buster

RUN apt-get update && apt-get install \
        --no-install-recommends -qq -y \
    build-essential \
    gcc \
    g++ \
    libpoppler-cpp-dev \
    poppler-utils \
    pkg-config \
    libpq-dev

WORKDIR /athena

COPY ./pylintrc /athena/pylintrc

COPY ./requirements.txt /athena/requirements.txt
COPY ./requirements-dev.txt /athena/requirements-dev.txt

RUN pip install --upgrade pip
RUN pip install -r /athena/requirements.txt -r /athena/requirements-dev.txt

COPY ./alembic.ini /athena/alembic.ini
COPY ./alembic /athena/alembic

COPY ./athena/constants /athena/constants
COPY ./athena/extensions /athena/extensions
COPY ./athena/serializers /athena/serializers
COPY ./athena/utils /athena/utils
COPY ./athena/api /athena/api

RUN rm requirements.txt \
    requirements-dev.txt \
    pylintrc

# CMD ["uvicorn", "api.main:api", "--host", "0.0.0.0", "--port", "8000"]