name: Docker Compose Actions Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Down containers
        run: docker-compose --env-file=compose.env down --remove-orphans

      - name: Build image
        run: docker-compose --env-file=compose.env build

      - name: Run project
        run: docker-compose --env-file=compose.env up

      # - name: Test
        # run: docker run --network container:webapp-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/