name: Deploy project

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    name: Run tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
    
    - name: Get project secrets
      env:
        ATHENA_PROJECT_SECRETS: ${{ secrets.ATHENA_PROJECT_SECRETS }}
      run: |
        echo $ATHENA_PROJECT_SECRETS | base64 -d > compose-prod.env
    
    - name: Build test image and run
      run: |
        docker compose --env-file=compose-prod.env --file=compose-tests.yaml down --remove-orphans
        docker compose --env-file=compose-prod.env --file=compose-tests.yaml build
        docker compose --env-file=compose-prod.env --file=compose-tests.yaml run ares-pylint
        docker compose --env-file=compose-prod.env --file=compose-tests.yaml run ares-flake8
        docker compose --env-file=compose-prod.env --file=compose-tests.yaml run ares-tests
        docker compose --env-file=compose-prod.env --file=compose-tests.yaml run apollo-pylint
        docker compose --env-file=compose-prod.env --file=compose-tests.yaml run apollo-flake8

  deploy:
    name: Deploy to EC2
    timeout-minutes: 5
    needs: run-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Get project secrets from secret
      env:
        ATHENA_PROJECT_SECRETS: ${{ secrets.ATHENA_PROJECT_SECRETS }}
      run: |
        echo $ATHENA_PROJECT_SECRETS | base64 -d > compose-prod.env

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        SOURCE: "./"

        SCRIPT_BEFORE: |
          echo "starting script before"
          echo "listing items"
          ls
          echo "items listed"
          mkdir -p project
          echo "script_before ended"
        SCRIPT_AFTER: |
          echo "starting script_after"
          cd project
          docker compose --env-file=compose-prod.env --file=compose-prod.yaml down --remove-orphans
          docker compose --env-file=compose-prod.env --file=compose-prod.yaml build
          docker compose --env-file=compose-prod.env --file=compose-prod.yaml up -d
          echo "removing dangling images"
          docker rmi -f $(docker images -f "dangling=true" -q)
          echo "script_after ended"

        EXCLUDE: |
          **/.env
          **/__pycache__
          **/*.pyc
          **/.git
          **/.code-workspace
          **/.github
          **/local_ssh_script-before.sh