name: Build test image

on: [ pull_request ]

jobs:
  run-tests:
    name: Run tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
    
    - name: Build test image and run
      run: |
        docker compose --env-file=compose-local.env --file=compose-tests.yaml down --remove-orphans
        docker compose --env-file=compose-local.env --file=compose-tests.yaml build
        docker compose --env-file=compose-local.env --file=compose-tests.yaml run ares-pylint
        docker compose --env-file=compose-local.env --file=compose-tests.yaml run ares-flake8
        docker compose --env-file=compose-local.env --file=compose-tests.yaml run ares-tests
        docker compose --env-file=compose-local.env --file=compose-tests.yaml run apollo-pylint
        docker compose --env-file=compose-local.env --file=compose-tests.yaml run apollo-flake8