name: Deploy

on: [ pull_request ]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: |
          docker-compose --env-file=compose.env --file=compose-tests.yaml down --remove-orphans
          docker-compose --env-file=compose.env --file=compose-tests.yaml build
          docker-compose --env-file=compose.env --file=compose-tests.yaml up --abort-on-container-exit