name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "compose-tests.yaml"
          down-flags: "--remove-orphans --volumes"
          up-flags: "--build"
        env:
          --env-file: "compose.env"
